service: aws-lambda-node
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:522536073208:table/Portfolio

functions:
  hello:
    handler: src/welcome.hello
    events:
      - httpApi:
          path: /
          method: get
    
  createUser:
    handler: src/addUser.addUser
    events:
      - httpApi:
          path: /user
          method: post

  getUsers:
    handler: src/getUsers.getUsers
    events:
      - httpApi:
          path: /user
          method: get

  getUser:
    handler: src/getUser.getUser
    events:
      - httpApi:
          path: /user/{id}
          method: get

  updateUser:
    handler: src/updateUser.updateUser
    events:
      - httpApi:
          path: /user/{id}
          method: put

  deleteUser:
    handler: src/deleteUser.deleteUser
    events:
      - httpApi:
          path: /user/{id}
          method: delete

resources:
  Resources:
    Portfolio:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Portfolio
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH